file:
  upload-dir: C:\Users\荣耀\AppData\Local\Temp
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  rabbitmq:
    host: 15.164.94.143
    port: 5672
    username: rabbit
    password: rabbit